<?php 

//V10

?>
<h2>Registro de usuario</h2><?php //V10 ?>

 <form name="form1" method="post" action=""><?php //V10 ?>
    <input type="hidden" value="1" name="enviar" /><?php //V10 ?>

     <p><?php //V10 ?>
        <label>Nombre: </label><?php //V10 ?>
        <input type="text" name="nombre" value="<?php if(isset($this->datos)) echo $this->datos['nombre']; ?>" /><?php //V10 ?>
    </p><?php //V10 ?>

     <p><?php //V10 ?>
        <label>Usuario: </label><?php //V10 ?>
        <input type="text" name="usuario" value="<?php if(isset($this->datos)) echo $this->datos['usuario']; ?>" /><?php //V10 ?>
    </p><?php //V10 ?>

     <p><?php //V10 ?>
        <label>Email: </label><?php //V10 ?>
        <input type="text" name="email" value="<?php if(isset($this->datos)) echo $this->datos['email']; ?>" /><?php //V10 ?>
    </p><?php //V10 ?>

     <p><?php //V10 ?>
        <label>Password: </label><?php //V10 ?>
        <input type="password" name="pass" /><?php //V10 ?>
    </p><?php //V10 ?>

     <p><?php //V10 ?>
        <label>Confirmar: </label><?php //V10 ?>
        <input type="password" name="confirmar" /><?php //V10 ?>
    </p><?php //V10 ?>

     <p><?php //V10 ?>
        <input type="submit" value="enviar" /><?php //V10 ?>
    </p><?php //V10 ?>
</form><?php //V10 ?>