<?php 

//V3 - V4

//echo $this->titulo;                 //V3

?>
<h2>BIENVENIDO</h2> <?php //V9 ?>
<!-- <h2>Vista  hola index...</h2> --> <?php //V3 ?>
<!--
<pre><?php //print_r($this->posts); //V4 ?></pre> 


<?php //if(isset($this->posts) && count($this->posts)): //V4 ?>

 <table> <?php //V4 ?>
	<?php //for($i = 0; $i < count($this->posts); $i++): //V4 ?>
		<tr> <?php //V4 ?>
			<td><?php //echo $this->posts[$i]['id']; //V4 ?></td>
			<td><?php //echo $this->posts[$i]['titulo']; //V4 ?></td>
			<td><?php //echo $this->posts[$i]['cuerpo']; //V4 ?></td>
		</tr> <?php //V4 ?>
	<?php //endfor; //V4 ?>
</table> <?php //V4 ?>

 <?php //else: //V4 ?>
	<p><strong>No hay post</strong></p> <?php //V4 ?>

 <?php //endif; //V4 ?>
 -->